package co.unicauca.microkernel.client.presentation;

import static co.unicauca.microkernel.client.access.Factory.getInstance;
import co.unicauca.microkernel.client.access.IClienteAccess;
import co.unicauca.microkernel.client.domain.ClienteService;
import co.unicauca.microkernel.client.gestionTabla.TablaCarritoEspeciales;
import co.unicauca.microkernel.client.gestionTabla.TablaCarritoEspecialesCf;
import co.unicauca.microkernel.client.gestionTabla.TablaCarritoRacion;
import co.unicauca.microkernel.client.gestionTabla.TablaCarritoRacionCf;
import co.unicauca.microkernel.client.gestionTabla.TablaEspecialesHaP;
import co.unicauca.microkernel.client.gestionTabla.TablaRacionesHaP;
import co.unicauca.microkernel.common.entities.CarritoG;
import co.unicauca.microkernel.common.entities.Pedido;
import co.unicauca.microkernel.common.entities.PlatoEspecial;
import co.unicauca.microkernel.common.entities.PlatoEspecialPed;
import co.unicauca.microkernel.common.entities.RacionDia;
import co.unicauca.microkernel.common.entities.RacionPed;
import co.unicauca.microkernel.common.infra.Utilities;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 * Interfaz donde se hace el pedido
 * @author Edynson, Jhonfer, Mateo, Camilo, James
 */
public class HacerPedido extends javax.swing.JFrame {
    //listas
    List<RacionDia> raciones;
    List<PlatoEspecial> especiales;
    List<CarritoG> carritoR;
    List<CarritoG> carritoE;
    //tablas
    TablaRacionesHaP tabRacionesHaP;
    TablaEspecialesHaP tabEspecialesHaP;
    TablaCarritoRacion tabCarritoR;
    TablaCarritoEspeciales tabCarritoE;
    TablaCarritoEspecialesCf tabCarritoECf;
    TablaCarritoRacionCf tabCarritoRCf;
    //servicios
    IClienteAccess service;
    ClienteService servicioRestaurante;
    
    private Pedido pedido;
    
    public HacerPedido(Pedido pedido, ClienteService cliente) throws Exception {
        // se inicializan los servicios
        service = getInstance().getClienteService();
        servicioRestaurante = new ClienteService(service);
        //sse inicializan las tablas
        tabRacionesHaP = new TablaRacionesHaP();
        tabEspecialesHaP = new TablaEspecialesHaP();
        tabCarritoR = new TablaCarritoRacion();
        tabCarritoE = new TablaCarritoEspeciales();
        tabCarritoRCf = new TablaCarritoRacionCf();
        tabCarritoECf = new TablaCarritoEspecialesCf();
        initComponents();
        //se inicializa el pedido
        this.pedido = pedido;
        //se inicializan las listas
        raciones = new ArrayList<>();
        especiales = new ArrayList<>();
        carritoR = new ArrayList<>();
        carritoE = new ArrayList<>();
        //se crean las tablas
        this.crearTablaCarritoRacionesCf(pedido.getIdPedido());
        this.crearTablaCarritoEspecialesCf(pedido.getIdPedido());
        this.crearTablaCarritoRaciones(pedido.getIdPedido());
        this.crearTablaCarritoEspeciales(pedido.getIdPedido());
        this.crearTablaRaciones();
        this.crearTablaEspeciales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblRaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRaciones = new javax.swing.JTable();
        lblImagenRaciones = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCarritoRaciones = new javax.swing.JTable();
        lblCarritoRaciones = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblPlatosEspeciales = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPlatosEspeciales = new javax.swing.JTable();
        lblImagenPlatos = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCarritoPlatos = new javax.swing.JTable();
        lblCarritosPlatos = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblCarritoRacionesCf = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblCarritoRacionesCf = new javax.swing.JTable();
        lblCarritoPlatosCf = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblCarritoPlatosCf = new javax.swing.JTable();
        btnConfirmarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(874, 491));

        jTabbedPane1.setBackground(new java.awt.Color(30, 100, 85));

        jPanel1.setBackground(new java.awt.Color(30, 100, 85));

        lblRaciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRaciones.setText("Raciones disponible para es dia: ");

        tblRaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "DIA", "TIPO", "PRECIO", "ACCION 1"
            }
        ));
        tblRaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRaciones);

        tblCarritoRaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "PRECIO", "CANTIDAD", "ACCION 1", "ACCION 2", "ACCION 3"
            }
        ));
        tblCarritoRaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCarritoRacionesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCarritoRaciones);

        lblCarritoRaciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCarritoRaciones.setText("Carrito Raciones: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRaciones)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCarritoRaciones)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblImagenRaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblRaciones)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCarritoRaciones)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblImagenRaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("COMPRAR RACIONES", jPanel1);

        jPanel2.setBackground(new java.awt.Color(30, 100, 85));

        lblPlatosEspeciales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPlatosEspeciales.setText("Platos especiales: ");

        tblPlatosEspeciales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "DESCRIPCION", "PRECIO", "ACCION 1"
            }
        ));
        tblPlatosEspeciales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPlatosEspecialesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPlatosEspeciales);

        tblCarritoPlatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "PRECIO", "CANTIDAD", "ACCION 1", "ACCION 2", "ACCION 3"
            }
        ));
        tblCarritoPlatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCarritoPlatosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblCarritoPlatos);

        lblCarritosPlatos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCarritosPlatos.setText("Carrito platos especiales:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblPlatosEspeciales)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCarritosPlatos)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(lblImagenPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblPlatosEspeciales)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCarritosPlatos)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblImagenPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("COMPRAR PLATOS ESPECIALES", jPanel2);

        jPanel3.setBackground(new java.awt.Color(30, 100, 85));

        lblCarritoRacionesCf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCarritoRacionesCf.setText("Carrito raciones: ");

        tblCarritoRacionesCf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "PRECIO", "CANTIDAD"
            }
        ));
        jScrollPane5.setViewportView(tblCarritoRacionesCf);

        lblCarritoPlatosCf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCarritoPlatosCf.setText("Carrito platos especiales: ");

        tblCarritoPlatosCf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "PRECIO", "CANTIDAD"
            }
        ));
        jScrollPane6.setViewportView(tblCarritoPlatosCf);

        btnConfirmarPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConfirmarPedido.setText("CONFIRMAR PEDIDO");
        btnConfirmarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarritoRacionesCf)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarritoPlatosCf))
                .addGap(21, 21, 21))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(btnConfirmarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarritoRacionesCf)
                    .addComponent(lblCarritoPlatosCf))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addComponent(btnConfirmarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CONFIRMAR PEDIDO", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblRacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRacionesMouseClicked
        int column = tblRaciones.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tblRaciones.getRowHeight();
        byte[] imagen = this.raciones.get(row).getImagen();
        this.servicioRestaurante.fijarImagen(this.lblImagenRaciones, imagen, "FOTONULA");
        if (row < tblRaciones.getRowCount() && row >= 0 && column < tblRaciones.getColumnCount() && column >= 0) {
            Object value = tblRaciones.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                var boton = (JButton) value;
                if (boton.getName().equals("CarritoR")) {
                    RacionPed aux = new RacionPed (pedido.getIdPedido(),this.raciones.get(row).getRacId(),1);
                    try {
                        this.servicioRestaurante.addRacionPedido(aux);
                        this.crearTablaCarritoRaciones(aux.getPedId());
                        this.crearTablaCarritoRacionesCf(aux.getPedId());
                    } catch (Exception ex) {
                        Logger.getLogger(FramePrincipalAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_tblRacionesMouseClicked

    private void tblPlatosEspecialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPlatosEspecialesMouseClicked
        int column = tblPlatosEspeciales.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tblPlatosEspeciales.getRowHeight();
        byte[] imagen = this.especiales.get(row).getImagen();
        this.servicioRestaurante.fijarImagen(this.lblImagenPlatos, imagen, "FOTONULA");
        if (row < tblPlatosEspeciales.getRowCount() && row >= 0 && column < tblRaciones.getColumnCount() && column >= 0) {
            Object value = tblPlatosEspeciales.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                var boton = (JButton) value;
                if (boton.getName().equals("CarritoE")) {
                    PlatoEspecialPed aux = new PlatoEspecialPed (pedido.getIdPedido(),this.especiales.get(row).getId_pe(),1);
                    try {
                        this.servicioRestaurante.addPlatoEspecialPedido(aux);
                        this.crearTablaCarritoEspeciales(aux.getPedId());
                        this.crearTablaCarritoEspecialesCf(aux.getPedId());
                    } catch (Exception ex) {
                        Logger.getLogger(FramePrincipalAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_tblPlatosEspecialesMouseClicked

    private void btnConfirmarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPedidoActionPerformed
        this.setVisible(false);
        ConfirmarPedido instancia;
        try {
            instancia = new ConfirmarPedido(pedido,this.servicioRestaurante);
            instancia.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(HacerPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnConfirmarPedidoActionPerformed

    private void tblCarritoRacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCarritoRacionesMouseClicked
        int column = tblCarritoRaciones.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tblCarritoRaciones.getRowHeight();
        if (row < tblCarritoRaciones.getRowCount() && row >= 0 && column < tblCarritoRaciones.getColumnCount() && column >= 0) {
            Object value = tblCarritoRaciones.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                var boton = (JButton) value;
                if (boton.getName().equals("Aumentar")) {
                    try {
                        this.servicioRestaurante.aumentarCantidad("RACION", this.carritoR.get(row).getIdCarrito(), this.carritoR.get(row).getCantidad());
                        this.crearTablaCarritoRaciones(this.pedido.getIdPedido());
                        this.crearTablaCarritoRacionesCf(this.pedido.getIdPedido());
                    } catch (Exception ex) {
                        Logger.getLogger(FramePrincipalAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (boton.getName().equals("Disminuir")) {
                    try {
                        this.servicioRestaurante.disminuirCantidad("RACION", this.carritoR.get(row).getIdCarrito(), this.carritoR.get(row).getCantidad());
                        this.crearTablaCarritoRaciones(this.pedido.getIdPedido());
                        this.crearTablaCarritoRacionesCf(this.pedido.getIdPedido());
                    } catch (Exception ex) {
                        Logger.getLogger(FramePrincipalAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (boton.getName().equals("Eliminar")) {
                    try {
                        this.servicioRestaurante.deleteRacionPedido(this.carritoR.get(row).getIdCarrito());
                        this.crearTablaCarritoRaciones(this.pedido.getIdPedido());
                        this.crearTablaCarritoRacionesCf(this.pedido.getIdPedido());
                    } catch (Exception ex) {
                        Logger.getLogger(FramePrincipalAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_tblCarritoRacionesMouseClicked

    private void tblCarritoPlatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCarritoPlatosMouseClicked
        int column = tblCarritoPlatos.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tblCarritoPlatos.getRowHeight();
        
        if (row < tblCarritoPlatos.getRowCount() && row >= 0 && column < tblCarritoPlatos.getColumnCount() && column >= 0) {
            Object value = tblCarritoPlatos.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                var boton = (JButton) value;
                if (boton.getName().equals("Aumentar")) {
                    try {
                        this.servicioRestaurante.aumentarCantidad("PLATO", this.carritoE.get(row).getIdCarrito(), this.carritoE.get(row).getCantidad());
                        this.crearTablaCarritoEspeciales(this.pedido.getIdPedido());
                        this.crearTablaCarritoEspecialesCf(this.pedido.getIdPedido());
                    } catch (Exception ex) {
                        Logger.getLogger(FramePrincipalAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (boton.getName().equals("Disminuir")) {
                    try {
                        this.servicioRestaurante.disminuirCantidad("PLATO", this.carritoE.get(row).getIdCarrito(), this.carritoE.get(row).getCantidad());
                        this.crearTablaCarritoEspeciales(this.pedido.getIdPedido());
                        this.crearTablaCarritoEspecialesCf(this.pedido.getIdPedido());
                    } catch (Exception ex) {
                        Logger.getLogger(FramePrincipalAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (boton.getName().equals("Eliminar")) {
                    try {
                        this.servicioRestaurante.deletePlatoEspecialPedido(this.carritoE.get(row).getIdCarrito());
                        this.crearTablaCarritoEspeciales(this.pedido.getIdPedido());
                        this.crearTablaCarritoEspecialesCf(this.pedido.getIdPedido());
                    } catch (Exception ex) {
                        Logger.getLogger(FramePrincipalAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_tblCarritoPlatosMouseClicked
    public void crearTablaCarritoEspecialesCf(int idPedido) throws Exception {
        this.tblCarritoPlatosCf.removeAll();
        this.serviceListarCarritoEspeciales(idPedido);
        tabCarritoECf.ver_tabla(tblCarritoPlatosCf, carritoE);
    }
    public void crearTablaCarritoRacionesCf(int idPedido) throws Exception {
        this.tblCarritoRacionesCf.removeAll();
        this.serviceListarCarritoRaciones(idPedido);
        tabCarritoRCf.ver_tabla(tblCarritoRacionesCf, carritoR);
    }
    public void crearTablaCarritoEspeciales(int idPedido) throws Exception {
        this.tblCarritoPlatos.removeAll();
        this.serviceListarCarritoEspeciales(idPedido);
        tabCarritoE.ver_tabla(tblCarritoPlatos, carritoE);
    }
    private void serviceListarCarritoEspeciales(int idPedido) throws Exception {
        this.carritoE = servicioRestaurante.listCarritoPlatoEspecial(pedido.getCliente(),idPedido,"comprador");
    }    
    public void crearTablaCarritoRaciones(int idPedido) throws Exception {
        this.tblCarritoRaciones.removeAll();
        this.serviceListarCarritoRaciones(idPedido);
        tabCarritoR.ver_tabla(tblCarritoRaciones, carritoR);
    }
    private void serviceListarCarritoRaciones(int idPedido) throws Exception {
        this.carritoR = servicioRestaurante.listCarritoRacion(pedido.getCliente(),idPedido,"comprador");
    }
    public void crearTablaRaciones() throws Exception {
        this.tblRaciones.removeAll();
        this.serviceListarRaciones();
        tabRacionesHaP.ver_tabla(tblRaciones, raciones);
    }
    private void serviceListarRaciones() throws Exception {
        this.raciones = servicioRestaurante.listMenuDay(pedido.getResId(),Utilities.DiaActual(),"administrador");
        System.out.println("tamaño: "+raciones.size());
    }
    public void crearTablaEspeciales() throws Exception {
        this.tblRaciones.removeAll();
        this.serviceListarEspeciales();
        tabEspecialesHaP.ver_tabla(tblPlatosEspeciales, especiales);
    }
    private void serviceListarEspeciales() throws Exception {
        this.especiales = servicioRestaurante.listMenuSpecial(pedido.getResId(), "administrador");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarPedido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCarritoPlatosCf;
    private javax.swing.JLabel lblCarritoRaciones;
    private javax.swing.JLabel lblCarritoRacionesCf;
    private javax.swing.JLabel lblCarritosPlatos;
    private javax.swing.JLabel lblImagenPlatos;
    private javax.swing.JLabel lblImagenRaciones;
    private javax.swing.JLabel lblPlatosEspeciales;
    private javax.swing.JLabel lblRaciones;
    private javax.swing.JTable tblCarritoPlatos;
    private javax.swing.JTable tblCarritoPlatosCf;
    private javax.swing.JTable tblCarritoRaciones;
    private javax.swing.JTable tblCarritoRacionesCf;
    private javax.swing.JTable tblPlatosEspeciales;
    private javax.swing.JTable tblRaciones;
    // End of variables declaration//GEN-END:variables
}
