/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.microkernel.client.presentation;

import co.unicauca.microkernel.client.access.Factory;
import co.unicauca.microkernel.client.access.IClienteAccess;
import co.unicauca.microkernel.client.domain.ClienteService;
import co.unicauca.microkernel.client.gestionTabla.TablaCarritoEspeciales;
import co.unicauca.microkernel.client.gestionTabla.TablaCarritoEspecialesCf;
import co.unicauca.microkernel.client.gestionTabla.TablaCarritoRacion;
import co.unicauca.microkernel.client.gestionTabla.TablaCarritoRacionCf;
import co.unicauca.microkernel.client.gestionTabla.TablaEspecialesHaP;
import co.unicauca.microkernel.client.gestionTabla.TablaRacionesHaP;
import co.unicauca.microkernel.common.entities.CarritoG;
import co.unicauca.microkernel.common.entities.CategoriaEnum;
import co.unicauca.microkernel.common.entities.Cliente;
import co.unicauca.microkernel.common.entities.ClienteCrypt;
import co.unicauca.microkernel.common.entities.Pedido;
import co.unicauca.microkernel.common.entities.PlatoEspecial;
import co.unicauca.microkernel.common.entities.RacionDia;
import co.unicauca.microkernel.common.entities.TipoClien;
import co.unicauca.microkernel.common.infra.Utilities;
import static java.awt.Image.SCALE_SMOOTH;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import static javax.swing.JFileChooser.APPROVE_OPTION;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author EdynsonMJ,JhonnyRosero,JhonferRuiz,JuanGonzales,JamesSilva
 */
public class RegistrarUsuario extends javax.swing.JFrame {

    IClienteAccess service;
    ClienteService servicioRegistro;
    String ruta;
    String tipoCliente;
    Cliente cliente;
    

    public RegistrarUsuario(ClienteService cliente) {
        service = Factory.getInstance().getClienteService();
        servicioRegistro = new ClienteService(service);
        initComponents();
        this.btnRegistrarse.setEnabled(false);
        tipoCliente = (String) this.cbxTipoCliente.getSelectedItem();
        ruta = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        lblNombreUsu = new javax.swing.JLabel();
        txtNombreUsu = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        btnSubir = new javax.swing.JButton();
        cbxTipoCliente = new javax.swing.JComboBox<>();
        lblContraseña = new javax.swing.JLabel();
        lblConfiContraseña = new javax.swing.JLabel();
        txtConfiContraseña = new javax.swing.JPasswordField();
        lblImagen = new javax.swing.JLabel();
        btnBajar = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        lblCarrera = new javax.swing.JLabel();
        txtCarrera = new javax.swing.JTextField();
        lblCalle = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 100, 85));

        lblTipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTipo.setText("Tipo de usuario:");

        lblNombreUsu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombreUsu.setText("Nombre de usuario:");

        txtNombreUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreUsuKeyReleased(evt);
            }
        });

        txtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContraseñaKeyReleased(evt);
            }
        });

        btnSubir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubir.setText("Subir Foto");
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });

        cbxTipoCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COMPRADOR", "ADMINISTRADOR" }));

        lblContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblContraseña.setText("Contraseña:");

        lblConfiContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConfiContraseña.setText("Confirmar contraseña:");

        txtConfiContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfiContraseñaKeyReleased(evt);
            }
        });

        btnBajar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBajar.setText("Borrar Foto");
        btnBajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajarActionPerformed(evt);
            }
        });

        btnRegistrarse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarse.setText("REGISTRARSE");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        lblCarrera.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCarrera.setText("Carrera:");

        txtCarrera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCarreraKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCarreraKeyTyped(evt);
            }
        });

        lblCalle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCalle.setText("Calle:");

        txtCalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCalleKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCalleKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCarrera))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCalle)
                                    .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblConfiContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreUsu, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreUsu, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtConfiContraseña, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                                .addComponent(btnBajar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSubir)
                            .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistrarse)
                .addGap(131, 131, 131))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipo)
                            .addComponent(cbxTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(lblNombreUsu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblContraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblConfiContraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtConfiContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCarrera)
                            .addComponent(lblCalle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBajar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
        var j = new JFileChooser();
        var fil = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        j.setFileFilter(fil);
        var s = j.showOpenDialog(this);
        if (s == APPROVE_OPTION) {
            ruta = j.getSelectedFile().getAbsolutePath();
            var imagen = new ImageIcon(ruta);
            this.lblImagen.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(this.lblImagen.getWidth(), this.lblImagen.getHeight(), SCALE_SMOOTH)));
        }
    }//GEN-LAST:event_btnSubirActionPerformed

    private void btnBajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajarActionPerformed
        this.lblImagen.setIcon(null);
        this.ruta="";
    }//GEN-LAST:event_btnBajarActionPerformed

    private void txtNombreUsuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreUsuKeyReleased
        habilitarInicio();
    }//GEN-LAST:event_txtNombreUsuKeyReleased

    private void txtContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaKeyReleased
        habilitarInicio();
    }//GEN-LAST:event_txtContraseñaKeyReleased

    private void txtConfiContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfiContraseñaKeyReleased
        habilitarInicio();
    }//GEN-LAST:event_txtConfiContraseñaKeyReleased

    private void txtCarreraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarreraKeyReleased
        habilitarInicio();
    }//GEN-LAST:event_txtCarreraKeyReleased

    private void txtCalleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCalleKeyReleased
        habilitarInicio();
    }//GEN-LAST:event_txtCalleKeyReleased

    private void txtCarreraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarreraKeyTyped
        char caracter = evt.getKeyChar();

        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCarreraKeyTyped

    private void txtCalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCalleKeyTyped
        char caracter = evt.getKeyChar();

        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCalleKeyTyped

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        if (!(this.txtConfiContraseña.getText().equals(this.txtContraseña.getText()))){
            JOptionPane.showConfirmDialog(rootPane, "LAS CONTRASEÑAS NO CONCUERDAN", "ERROR", JOptionPane.CLOSED_OPTION);
            this.limpiarCampos();
            return;
        }
        String tipo = (String) this.cbxTipoCliente.getSelectedItem();
        String lowerTipo = tipo.toLowerCase();
        if (!this.ruta.equals("")){
            var imagen = Utilities.convertirFoto(this.ruta);
            cliente = new ClienteCrypt(this.txtNombreUsu.getText(),Integer.parseInt(this.txtCarrera.getText()),Integer.parseInt(this.txtCalle.getText()),TipoClien.valueOf(tipo),this.txtContraseña.getText(),imagen);
        }else{
            cliente = new ClienteCrypt(this.txtNombreUsu.getText(),Integer.parseInt(this.txtCarrera.getText()),Integer.parseInt(this.txtCalle.getText()),TipoClien.valueOf(tipo),this.txtContraseña.getText(),null);
        }
        try {
            if (servicioRegistro.registrarCliente(cliente, lowerTipo)== null) {
                JOptionPane.showConfirmDialog(rootPane, "Fallo", "ERROR", JOptionPane.CLOSED_OPTION);
            } else {
                JOptionPane.showConfirmDialog(rootPane, "Exito", "OK", JOptionPane.CLOSED_OPTION);
                this.setVisible(false);
                this.dispose();
            }
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(rootPane, "ERROR FATAL, NO SE PUDO CUMPLIR LA PETICION, REVISE LOS DATOS DIGITADOS", "ERROR", JOptionPane.CLOSED_OPTION);
            Logger.getLogger(AgregarRacion.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
            
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void limpiarCampos() {
        this.txtConfiContraseña.setText("");
        this.txtContraseña.setText("");
    }

    private void habilitarInicio() {

        if (this.txtNombreUsu.getText().isBlank() || this.txtContraseña.getText().isBlank() || this.txtCalle.getText().isBlank()
                || this.txtCarrera.getText().isBlank() || this.txtConfiContraseña.getText().isBlank()) {
            this.btnRegistrarse.setEnabled(false);
        } else {
            this.btnRegistrarse.setEnabled(true);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBajar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnSubir;
    private javax.swing.JComboBox<String> cbxTipoCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCalle;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblConfiContraseña;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombreUsu;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JPasswordField txtConfiContraseña;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtNombreUsu;
    // End of variables declaration//GEN-END:variables

}
